import { Equipment, Event, Incident, TeamMember } from './types';

export const mockEquipment: Equipment[] = [
  {
    id: 'eq-001',
    name: 'Console Son DiGiCo SD12',
    category: 'sound',
    qrCode: 'QR-SOUND-001',
    status: 'ok',
    location: 'Régie Son',
    zone: 'FOH',
    responsiblePerson: 'Marie Lambert',
    lastCheck: new Date('2026-02-10T18:30:00'),
    position: { x: 120, y: 80 },
  },
  {
    id: 'eq-002',
    name: 'Projecteur LED Robe BMFL',
    category: 'light',
    qrCode: 'QR-LIGHT-002',
    status: 'hs',
    location: 'Gril',
    zone: 'Cour',
    responsiblePerson: 'Thomas Dubois',
    lastCheck: new Date('2026-02-11T10:00:00'),
    position: { x: 80, y: 120, z: 8 },
    notes: 'Lampe défectueuse, remplacement nécessaire',
  },
  {
    id: 'eq-003',
    name: 'Écran LED 4x3m',
    category: 'video',
    qrCode: 'QR-VIDEO-003',
    status: 'to-check',
    location: 'Fond de scène',
    zone: 'Jardin',
    responsiblePerson: 'Sophie Martin',
    lastCheck: new Date('2026-02-09T14:00:00'),
    position: { x: 200, y: 150 },
    notes: 'Calibration à vérifier',
  },
  {
    id: 'eq-004',
    name: 'Haut-parleur L-Acoustics K2',
    category: 'sound',
    qrCode: 'QR-SOUND-004',
    status: 'ok',
    location: 'PA Principale',
    zone: 'Jardin',
    responsiblePerson: 'Marie Lambert',
    lastCheck: new Date('2026-02-11T08:00:00'),
    position: { x: 50, y: 60, z: 5 },
  },
  {
    id: 'eq-005',
    name: 'Machinerie Cinétique - Praticable',
    category: 'set',
    qrCode: 'QR-SET-005',
    status: 'repair',
    location: 'Plateau',
    zone: 'Centre',
    responsiblePerson: 'Jean Moreau',
    lastCheck: new Date('2026-02-10T16:00:00'),
    position: { x: 180, y: 100 },
    notes: 'Moteur en maintenance préventive',
  },
  {
    id: 'eq-006',
    name: 'Console Lumière GrandMA3',
    category: 'light',
    qrCode: 'QR-LIGHT-006',
    status: 'ok',
    location: 'Régie Lumière',
    zone: 'FOH',
    responsiblePerson: 'Thomas Dubois',
    lastCheck: new Date('2026-02-11T09:00:00'),
    position: { x: 140, y: 75 },
  },
  {
    id: 'eq-007',
    name: 'Harnais de Sécurité',
    category: 'safety',
    qrCode: 'QR-SAFETY-007',
    status: 'to-check',
    location: 'Local Sécurité',
    responsiblePerson: 'Claire Rousseau',
    lastCheck: new Date('2026-02-05T12:00:00'),
    notes: 'Vérification annuelle due',
  },
  {
    id: 'eq-008',
    name: 'Projecteur Fresnel 2kW',
    category: 'light',
    qrCode: 'QR-LIGHT-008',
    status: 'ok',
    location: 'Perche Cour',
    zone: 'Cour',
    responsiblePerson: 'Thomas Dubois',
    lastCheck: new Date('2026-02-10T17:00:00'),
    position: { x: 90, y: 140, z: 6 },
  },
];

export const mockEvents: Event[] = [
  {
    id: 'evt-001',
    title: 'Hamlet - Représentation',
    startDate: new Date('2026-02-11T20:00:00'),
    endDate: new Date('2026-02-11T23:00:00'),
    venue: 'Théâtre National',
    stage: 'Grande Salle',
    checklistProgress: 78,
    equipmentIds: ['eq-001', 'eq-003', 'eq-004', 'eq-006', 'eq-008'],
    teamMembers: ['tm-001', 'tm-002', 'tm-003', 'tm-004'],
    status: 'setup',
  },
  {
    id: 'evt-002',
    title: 'Le Malade Imaginaire - Répétition Générale',
    startDate: new Date('2026-02-12T14:00:00'),
    endDate: new Date('2026-02-12T18:00:00'),
    venue: 'Théâtre National',
    stage: 'Salle Studio',
    checklistProgress: 45,
    equipmentIds: ['eq-005', 'eq-007'],
    teamMembers: ['tm-001', 'tm-005'],
    status: 'planning',
  },
  {
    id: 'evt-003',
    title: 'Concert Symphonique - Installation',
    startDate: new Date('2026-02-13T10:00:00'),
    endDate: new Date('2026-02-13T16:00:00'),
    venue: 'Salle Pleyel',
    stage: 'Scène Principale',
    checklistProgress: 12,
    equipmentIds: ['eq-001', 'eq-004'],
    teamMembers: ['tm-001', 'tm-002'],
    status: 'planning',
  },
];

export const mockIncidents: Incident[] = [
  {
    id: 'inc-001',
    title: 'Panne projecteur BMFL',
    description: 'La lampe ne s\'allume plus. Alimentation testée OK. Remplacement de la lampe nécessaire.',
    severity: 'high',
    status: 'in-progress',
    equipmentId: 'eq-002',
    reportedBy: 'Thomas Dubois',
    timestamp: new Date('2026-02-11T10:15:00'),
  },
  {
    id: 'inc-002',
    title: 'Calibration écran LED',
    description: 'Couleurs désaturées sur le panneau inférieur gauche. Calibration recommandée.',
    severity: 'medium',
    status: 'open',
    equipmentId: 'eq-003',
    reportedBy: 'Sophie Martin',
    timestamp: new Date('2026-02-11T08:45:00'),
  },
  {
    id: 'inc-003',
    title: 'Maintenance praticable',
    description: 'Maintenance préventive planifiée du moteur. Pièces commandées.',
    severity: 'low',
    status: 'in-progress',
    equipmentId: 'eq-005',
    reportedBy: 'Jean Moreau',
    timestamp: new Date('2026-02-10T16:30:00'),
  },
  {
    id: 'inc-004',
    title: 'Vérification harnais annuelle',
    description: 'Contrôle annuel obligatoire des équipements de sécurité en hauteur.',
    severity: 'medium',
    status: 'open',
    equipmentId: 'eq-007',
    reportedBy: 'Claire Rousseau',
    timestamp: new Date('2026-02-11T09:00:00'),
  },
  {
    id: 'inc-005',
    title: 'Interférence micro HF',
    description: 'Interférences détectées sur la fréquence 650MHz. Résolu par changement de canal.',
    severity: 'medium',
    status: 'resolved',
    equipmentId: 'eq-001',
    reportedBy: 'Marie Lambert',
    timestamp: new Date('2026-02-10T19:30:00'),
    resolvedAt: new Date('2026-02-10T19:45:00'),
    resolutionNotes: 'Canal changé de 650MHz à 680MHz. Test OK.',
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm-001',
    name: 'Marie Lambert',
    role: 'Régisseur Son',
    email: 'marie.lambert@theatre.fr',
    phone: '+33 6 12 34 56 78',
    permissions: ['sound', 'incidents', 'equipment'],
  },
  {
    id: 'tm-002',
    name: 'Thomas Dubois',
    role: 'Régisseur Lumière',
    email: 'thomas.dubois@theatre.fr',
    phone: '+33 6 23 45 67 89',
    permissions: ['light', 'incidents', 'equipment'],
  },
  {
    id: 'tm-003',
    name: 'Sophie Martin',
    role: 'Régisseur Vidéo',
    email: 'sophie.martin@theatre.fr',
    phone: '+33 6 34 56 78 90',
    permissions: ['video', 'incidents', 'equipment'],
  },
  {
    id: 'tm-004',
    name: 'Jean Moreau',
    role: 'Régisseur Plateau',
    email: 'jean.moreau@theatre.fr',
    phone: '+33 6 45 67 89 01',
    permissions: ['set', 'rigging', 'incidents', 'equipment', 'admin'],
  },
  {
    id: 'tm-005',
    name: 'Claire Rousseau',
    role: 'Responsable Sécurité',
    email: 'claire.rousseau@theatre.fr',
    phone: '+33 6 56 78 90 12',
    permissions: ['safety', 'incidents', 'equipment', 'admin'],
  },
];
